### ISSUE TITLE
Backend : Implement a Admin Login page

### ISSUE THREAD

**Issue by iamurmani** [iamurmani/skilluptechie#10]
**NOTE**
This is connected to  [UI task](https://github.com/iamurmani/skilluptechie/issues/9 ) please communicate with the developer working on this ticket to avoid confusion.

1. Authentication:

- Create an API to Authenticate admin credentials against a secure backend system.
- Utilize encryption techniques to securely store and transmit sensitive information like passwords.
2. Dashboard Access:

- Once authenticated, grant access to the admin dashboard.
- Redirect the admin to the dashboard page upon successful login.
- Ensure that only authenticated admins can access the dashboard by implementing appropriate middleware or authentication guards.

3. Error Handling:

- Handle various scenarios such as invalid credentials, server errors, or network issues gracefully.
Provide informative error messages to guide admins in case of login failures.

**Comment by mani627** [comment]
hi @iamurmani bro, kindly review my code and revert.
