### ISSUE TITLE
Navigation Bar for Admin Dashboard

### ISSUE THREAD

**Issue by iamurmani** [iamurmani/skilluptechie#11]
### Overview
The feature involves implementing a navigation menu for the admin dashboard, with the ability to easily add and remove menu items.

### Key Components
1. **Navigation Menu**:
   - Create a navigation menu component specifically designed for the admin dashboard.
   - Include UI elements such as links or buttons to represent different menu items.

2. **Dynamic Menu Items**:
   - Implement functionality to allow dynamic addition and removal of menu items.
   - Provide an easy-to-use interface for administrators to manage menu items.

3. **Configuration Options**:
   - Offer configuration options for each menu item, including label, icon, and target URL.

4. **Persistence**:
   - Store menu configuration settings persistently, such as in configuration file.

[Figma Design](https://www.figma.com/file/g8O1G7GbRC8lTOW3QdJRNj/InterviewPrep?type=design&node-id=26-549&mode=design)

<img width="226" alt="image" src="https://github.com/iamurmani/skilluptechie/assets/54367953/270c97a6-fa62-4ffd-afab-04db4b743755">

**Comment by Madanraj0519** [comment]
Hii @iamurmani, I am interested in doing this task could you plz assign this to me

**Comment by Madanraj0519** [comment]
Hi @iamurmani, It is in the finishing stage.
![Screenshot 2024-05-20 233036](https://github.com/iamurmani/skilluptechie/assets/125730836/fa0c9e90-454f-41fc-a914-759d69ffd048)

**Comment by iamurmani** [comment]
@Madanraj0519 When can i except this task ? Do you need any support?

**Comment by Madanraj0519** [comment]
I have finished 80% of the work except the logo. I have an interview on Monday. I am preparing for that. Because of that it's taking time to complete. once, I finished and I will give the Pr


https://github.com/iamurmani/skilluptechie/assets/125730836/67722a08-996c-40ec-a5d4-ea14d613ae89

**Comment by iamurmani** [comment]
@Madanraj0519 Great, all the very best for your interview.

**Comment by Madanraj0519** [comment]
Hi @iamurmani, I finished all the things except the logo in the admin sidebar, I am having a problem with that, I don't know why the image is not rendering.

![Screenshot 2024-05-20 233036](https://github.com/iamurmani/skilluptechie/assets/125730836/4bf23a80-d39f-4c85-b801-b3e4ffc54616)

**Comment by iamurmani** [comment]
@Madanraj0519 Raise PR for the changes you made logo i will check while integrating

**Comment by Madanraj0519** [comment]
I Raised PR, You can check it @iamurmani
