### ISSUE TITLE
Frontend : Implement a Admin Login page

### ISSUE THREAD

**Issue by iamurmani** [iamurmani/skilluptechie#9]
**NOTE**
This is connected to  [Backend task](https://github.com/iamurmani/skilluptechie/issues/10) please communicate with the developer working on this ticket to avoid confusion.

1. Admin Login Page:

- Create a dedicated login page designed for administrators to enter their credentials.
- Include input fields for username/email and password.
- Implement validation to ensure the correctness of the provided credentials.
- Upon successful authentication, redirect the admin to the dashboard.

2. Route Configuration:

- Set up a route in the application specifically for the admin login page.
- The route should be structured as /admin/login to distinguish it from other routes.

[Figma Design](https://www.figma.com/file/g8O1G7GbRC8lTOW3QdJRNj/InterviewPrep?type=design&node-id=24-2&mode=design)

<img width="747" alt="image" src="https://github.com/iamurmani/skilluptechie/assets/54367953/0126a29f-f3d3-4f06-a553-4c7cece201d7">

**Comment by Abdul-Malik20** [comment]
Hello @iamurmani  bro, i have taken this task to work ! thank you

**Comment by iamurmani** [comment]
@Abdul-Malik20 take pull from env-changes branch this has fix for env issue and tailwind and MUI libraries are install installed in this branch. Please use these libraries for your development.

**Comment by Madanraj0519** [comment]
Hey @iamurmani, I am interested in this issue. would you assign me to this?
